### PR TITLE
ProxyServer support added

### PR DESCRIPTION
**Pull request by casetalk**
ProxyServer calls and configuration added (only for Indy)
Ignore most changes and new files, with the exception of the changes in the "src" folder.

### CODE REVIEW

**Comment by p-samuel** [comment]
Will be reviewing shortly.

**Comment by casetalk** [comment]
Btw. Subscribe without subscrive fails. Perhaps you could add an internal state 'isSubscribed' somewhere to make sure it doesn't raise unnecessary exceptions? Otherwise the caller needs to keep track of the isSubscribed state outside of this library.

**Comment by p-samuel** [comment]
> Btw. Unsubscribe without Subscribe fails. Perhaps you could add an internal state 'isSubscribed' somewhere to make sure it doesn't raise unnecessary exceptions? Otherwise the caller needs to keep track of the isSubscribed state outside of this library.

That's something I've been thinking about and it can be a bit little cumbersome to implement. It makes sense if you are subscribing to only one topic, but the problem arises when there are multiple topics on your connection string. How do you detect which topic are you willing to unsubscribe from?. e.g.: `ntfy.sh//topic1,topic2, topic3/json`.

**Review by p-samuel — APPROVED** [review]
Changes Reviewed

**Comment by p-samuel** [comment]
@casetalk, I added you as a contributor and rebased your branch as there were many unnecessary modified files. Thanks for your contribution.🙂

**Pull request merged**
